filebeat.inputs:
  - type: log
    paths:
      - /usr/share/jenkins/jobs/*/builds/*/*log
    multiline.pattern: 'TASK'
    multiline.negate: true
    multiline.match: after

output.logstash:
  hosts: ["logstash:5044"]
